<script setup lang="ts">
import { computed } from 'vue'
import { useAppStore } from '../../stores/appStore'
const { currentUser, students, programmes, sessions } = useAppStore()
const student = computed(() => students.value.find(item => item.email.toLowerCase() === currentUser.value?.email.toLowerCase()))
const programme = computed(() => programmes.value.find(item => item.id === student.value?.programmeId))
const session = computed(() => sessions.value.find(item => item.id === student.value?.sessionId))
</script>
<template>
  <div v-if="student" class="space-y-5"><div><p class="text-xs font-medium uppercase tracking-wider text-gold-600">Student Account</p><h2 class="font-serif text-2xl font-semibold text-navy-900">My Profile</h2><p class="text-sm text-navy-500">Your personal and academic information.</p></div><section class="rounded-xl bg-navy-800 p-6 text-white"><div class="flex items-center gap-4"><div class="flex h-16 w-16 items-center justify-center rounded-full bg-gold-400 font-serif text-xl font-bold text-navy-950">{{ student.name.split(' ').map(name => name[0]).slice(0, 2).join('') }}</div><div><h3 class="font-serif text-xl font-semibold">{{ student.name }}</h3><p class="text-sm text-navy-300">{{ student.studentId }} · {{ programme?.name }}</p><span class="mt-2 inline-block rounded-full bg-emerald-400/15 px-2 py-1 text-xs text-emerald-300">{{ student.status }}</span></div></div></section><section class="rounded-xl border border-navy-100 bg-white p-5"><h3 class="mb-4 font-serif font-semibold text-navy-900">Personal Information</h3><div class="grid gap-4 sm:grid-cols-2"><div><div class="text-xs text-navy-400">Full Name</div><div class="font-medium text-navy-800">{{ student.name }}</div></div><div><div class="text-xs text-navy-400">Student ID</div><div class="font-mono text-sm text-navy-800">{{ student.studentId }}</div></div><div><div class="text-xs text-navy-400">Email</div><div class="text-navy-800">{{ student.email }}</div></div><div><div class="text-xs text-navy-400">Phone</div><div class="text-navy-800">{{ student.phone || 'Not provided' }}</div></div><div><div class="text-xs text-navy-400">Roll Number</div><div class="font-mono text-sm text-navy-800">{{ student.rollNumber }}</div></div></div></section><section class="rounded-xl border border-navy-100 bg-white p-5"><h3 class="mb-4 font-serif font-semibold text-navy-900">Academic Information</h3><div class="grid gap-4 sm:grid-cols-2"><div><div class="text-xs text-navy-400">Programme</div><div class="font-medium text-navy-800">{{ programme?.name }}</div></div><div><div class="text-xs text-navy-400">Department</div><div class="text-navy-800">{{ programme?.department }}</div></div><div><div class="text-xs text-navy-400">Academic Session</div><div class="text-navy-800">{{ session?.name }}</div></div><div><div class="text-xs text-navy-400">Current Semester</div><div class="text-navy-800">Semester {{ student.currentSemester }}</div></div><div><div class="text-xs text-navy-400">Enrolled</div><div class="text-navy-800">{{ student.enrolledAt }}</div></div><div><div class="text-xs text-navy-400">Status</div><div class="text-navy-800">{{ student.status }}</div></div></div></section></div><div v-else class="rounded-xl border border-amber-200 bg-amber-50 p-6 text-sm text-amber-800">No student record is linked to this account.</div>
</template>
