<script setup lang="ts">
import { computed, ref } from 'vue'
import { useAppStore } from '../../stores/appStore'
import type { AcademicSession, AssessmentComponent, Programme, Semester, Subject } from '../../types'

type Tab = 'programmes' | 'sessions' | 'semesters' | 'subjects' | 'grading'
const { programmes, sessions, semesters, subjects, gradeRules, setProgrammes, setSessions, setSemesters, setSubjects } = useAppStore()
const tab = ref<Tab>('programmes')
const modal = ref<Tab | null>(null)
const editing = ref<string | null>(null)
const inputCls = 'w-full border border-navy-200 rounded-lg px-3 py-2.5 text-sm text-navy-900 focus:outline-none focus:border-navy-500'
const tabs = [['programmes', 'Programmes'], ['sessions', 'Academic Sessions'], ['semesters', 'Semesters'], ['subjects', 'Courses / Subjects'], ['grading', 'Grading System']] as const
const programmeForm = ref({ name: '', department: '', duration: 4, totalSemesters: 8 })
const sessionForm = ref({ name: '', startYear: 2024, endYear: 2025, status: 'active' as AcademicSession['status'] })
const semesterForm = ref({ number: 1, name: 'Semester 1', programmeId: '', sessionId: '', status: 'open' as Semester['status'] })
const subjectForm = ref({ code: '', title: '', credits: 3, semesterNumber: 1, programmeId: '', passMark: 50, components: [{ name: 'Internal', maxMarks: 30 }, { name: 'External', maxMarks: 70 }] as AssessmentComponent[] })
const title = computed(() => editing.value ? `Edit ${modal.value?.slice(0, -1)}` : `Add ${modal.value?.slice(0, -1)}`)
function openAdd(type: Tab) { editing.value = null; modal.value = type; if (type === 'programmes') programmeForm.value = { name: '', department: '', duration: 4, totalSemesters: 8 }; if (type === 'sessions') sessionForm.value = { name: '', startYear: 2024, endYear: 2025, status: 'active' }; if (type === 'semesters') semesterForm.value = { number: 1, name: 'Semester 1', programmeId: programmes.value[0]?.id ?? '', sessionId: sessions.value[0]?.id ?? '', status: 'open' }; if (type === 'subjects') subjectForm.value = { code: '', title: '', credits: 3, semesterNumber: 1, programmeId: programmes.value[0]?.id ?? '', passMark: 50, components: [{ name: 'Internal', maxMarks: 30 }, { name: 'External', maxMarks: 70 }] } }
function openEdit(type: Tab, item: Programme | AcademicSession | Semester | Subject) { editing.value = item.id; modal.value = type; if (type === 'programmes') programmeForm.value = { name: (item as Programme).name, department: (item as Programme).department, duration: (item as Programme).duration, totalSemesters: (item as Programme).totalSemesters }; if (type === 'sessions') sessionForm.value = { name: (item as AcademicSession).name, startYear: (item as AcademicSession).startYear, endYear: (item as AcademicSession).endYear, status: (item as AcademicSession).status }; if (type === 'semesters') semesterForm.value = { number: (item as Semester).number, name: (item as Semester).name, programmeId: (item as Semester).programmeId, sessionId: (item as Semester).sessionId, status: (item as Semester).status }; if (type === 'subjects') subjectForm.value = { ...(item as Subject), components: [...(item as Subject).components] } }
function save() { if (modal.value === 'programmes') setProgrammes(items => editing.value ? items.map(item => item.id === editing.value ? { ...item, ...programmeForm.value } : item) : [...items, { id: `p${Date.now()}`, ...programmeForm.value, status: 'active' }]); if (modal.value === 'sessions') setSessions(items => editing.value ? items.map(item => item.id === editing.value ? { ...item, ...sessionForm.value } : item) : [...items, { id: `s${Date.now()}`, ...sessionForm.value }]); if (modal.value === 'semesters') setSemesters(items => editing.value ? items.map(item => item.id === editing.value ? { ...item, ...semesterForm.value } : item) : [...items, { id: `sem${Date.now()}`, ...semesterForm.value, name: semesterForm.value.name || `Semester ${semesterForm.value.number}` }]); if (modal.value === 'subjects') setSubjects(items => editing.value ? items.map(item => item.id === editing.value ? { ...item, ...subjectForm.value } : item) : [...items, { id: `sub${Date.now()}`, ...subjectForm.value }]); modal.value = null }
function remove(type: Tab, id: string) { if (!window.confirm('Delete this academic record?')) return; if (type === 'programmes') setProgrammes(items => items.filter(item => item.id !== id)); if (type === 'sessions') setSessions(items => items.filter(item => item.id !== id)); if (type === 'semesters') setSemesters(items => items.filter(item => item.id !== id)); if (type === 'subjects') setSubjects(items => items.filter(item => item.id !== id)) }
function addComponent() { subjectForm.value.components.push({ name: '', maxMarks: 0 }) }
</script>
<template>
  <div class="space-y-6"><div class="bg-white border border-navy-100 rounded-xl overflow-hidden"><div class="flex border-b border-navy-100 overflow-x-auto"><button v-for="item in tabs" :key="item[0]" class="px-5 py-3.5 text-sm font-medium whitespace-nowrap border-b-2" :class="tab === item[0] ? 'border-navy-800 text-navy-900' : 'border-transparent text-navy-400'" @click="tab = item[0]">{{ item[1] }}</button></div><div class="p-6">
    <section v-if="tab === 'programmes'"><div class="flex justify-between mb-4"><div><h2 class="font-serif text-navy-900 font-semibold">Academic Programmes</h2><p class="text-navy-400 text-xs mt-0.5">{{ programmes.length }} programmes configured</p></div><button class="bg-navy-800 text-white px-4 py-2 rounded-lg text-sm" @click="openAdd('programmes')">+ Add Programme</button></div><div class="space-y-3"><div v-for="item in programmes" :key="item.id" class="flex items-center justify-between p-4 border border-navy-100 rounded-lg"><div><div class="text-sm font-medium text-navy-900">{{ item.name }}</div><div class="text-xs text-navy-400 mt-0.5">{{ item.department }} · {{ item.duration }} years · {{ item.totalSemesters }} semesters</div></div><div class="flex gap-4 items-center"><span class="text-xs px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-700">{{ item.status }}</span><button class="text-xs text-navy-500" @click="openEdit('programmes', item)">Edit</button><button class="text-xs text-red-600" @click="remove('programmes', item.id)">Delete</button></div></div></div></section>
    <section v-else-if="tab === 'sessions'"><div class="flex justify-between mb-4"><div><h2 class="font-serif text-navy-900 font-semibold">Academic Sessions</h2><p class="text-navy-400 text-xs mt-0.5">{{ sessions.length }} sessions</p></div><button class="bg-navy-800 text-white px-4 py-2 rounded-lg text-sm" @click="openAdd('sessions')">+ Add Session</button></div><div class="space-y-3"><div v-for="item in sessions" :key="item.id" class="flex items-center justify-between p-4 border border-navy-100 rounded-lg"><div><div class="text-sm font-medium text-navy-900">{{ item.name }}</div><div class="text-xs text-navy-400 mt-0.5">{{ item.startYear }}–{{ item.endYear }}</div></div><div class="flex gap-4 items-center"><span class="text-xs px-2 py-0.5 rounded-full bg-blue-50 text-blue-700">{{ item.status }}</span><button class="text-xs text-navy-500" @click="openEdit('sessions', item)">Edit</button><button class="text-xs text-red-600" @click="remove('sessions', item.id)">Delete</button></div></div></div></section>
    <section v-else-if="tab === 'semesters'"><div class="flex justify-between mb-4"><div><h2 class="font-serif text-navy-900 font-semibold">Semesters</h2><p class="text-navy-400 text-xs">{{ semesters.length }} semesters configured</p></div><button class="bg-navy-800 text-white px-4 py-2 rounded-lg text-sm" @click="openAdd('semesters')">+ Add Semester</button></div><table class="w-full text-sm"><thead><tr class="text-xs text-navy-500 uppercase border-b border-navy-100 text-left"><th class="pb-3">Semester</th><th class="pb-3">Programme</th><th class="pb-3">Session</th><th class="pb-3">Status</th><th /></tr></thead><tbody class="divide-y divide-navy-50"><tr v-for="item in semesters" :key="item.id"><td class="py-3 font-medium">{{ item.name }}</td><td class="py-3 text-xs">{{ programmes.find(programme => programme.id === item.programmeId)?.name ?? '—' }}</td><td class="py-3 text-xs">{{ sessions.find(session => session.id === item.sessionId)?.name ?? '—' }}</td><td class="py-3 text-xs">{{ item.status.replace('_', ' ') }}</td><td class="py-3"><button class="text-xs mr-3" @click="openEdit('semesters', item)">Edit</button><button class="text-xs text-red-600" @click="remove('semesters', item.id)">Del</button></td></tr></tbody></table></section>
    <section v-else-if="tab === 'subjects'"><div class="flex justify-between mb-4"><div><h2 class="font-serif text-navy-900 font-semibold">Courses / Subjects</h2><p class="text-navy-400 text-xs">{{ subjects.length }} subjects configured</p></div><button class="bg-navy-800 text-white px-4 py-2 rounded-lg text-sm" @click="openAdd('subjects')">+ Add Subject</button></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="text-xs text-navy-500 uppercase border-b border-navy-100 text-left"><th class="pb-3">Code</th><th class="pb-3">Title</th><th class="pb-3">Programme</th><th class="pb-3">Sem</th><th class="pb-3">Credits</th><th class="pb-3">Components</th><th /></tr></thead><tbody class="divide-y divide-navy-50"><tr v-for="item in subjects" :key="item.id"><td class="py-3 font-mono text-xs">{{ item.code }}</td><td class="py-3 font-medium">{{ item.title }}</td><td class="py-3 text-xs">{{ programmes.find(programme => programme.id === item.programmeId)?.name ?? '—' }}</td><td class="py-3">{{ item.semesterNumber }}</td><td class="py-3">{{ item.credits }}</td><td class="py-3 text-xs">{{ item.components.map(component => `${component.name}(${component.maxMarks})`).join(' + ') }}</td><td class="py-3"><button class="text-xs mr-3" @click="openEdit('subjects', item)">Edit</button><button class="text-xs text-red-600" @click="remove('subjects', item.id)">Del</button></td></tr></tbody></table></div></section>
    <section v-else><div class="mb-4"><h2 class="font-serif text-navy-900 font-semibold">Grading System</h2><p class="text-navy-400 text-xs">Current grading rules used for marks and GPA calculations. Changes are managed through the configured rules.</p></div><div class="grid grid-cols-2 gap-3 sm:grid-cols-4"><div v-for="rule in gradeRules" :key="rule.grade" class="rounded-lg border border-navy-100 bg-navy-50/50 p-4"><div class="font-mono text-xl font-bold text-gold-600">{{ rule.grade }}</div><div class="mt-1 text-xs text-navy-500">{{ rule.minMarks }}–{{ rule.maxMarks }} marks</div><div class="mt-2 text-xs font-semibold text-navy-700">{{ rule.gradePoint.toFixed(1) }} points</div><div class="mt-1 text-[11px] uppercase text-navy-400">{{ rule.passStatus }}</div></div></div></section>
  </div></div>
  <div v-if="modal" class="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4"><div class="bg-white rounded-xl shadow-xl w-full max-w-lg max-h-[90vh] overflow-y-auto"><div class="flex justify-between p-5 border-b border-navy-100"><h3 class="font-serif font-semibold">{{ title }}</h3><button class="text-xl" @click="modal = null">×</button></div><div class="p-5 space-y-4">
    <template v-if="modal === 'programmes'"><label class="block text-sm">Programme Name<input v-model="programmeForm.name" :class="inputCls" /></label><label class="block text-sm">Department<input v-model="programmeForm.department" :class="inputCls" /></label><div class="grid grid-cols-2 gap-4"><label class="block text-sm">Duration<input v-model.number="programmeForm.duration" type="number" :class="inputCls" /></label><label class="block text-sm">Total Semesters<input v-model.number="programmeForm.totalSemesters" type="number" :class="inputCls" /></label></div></template>
    <template v-else-if="modal === 'sessions'"><label class="block text-sm">Session Name<input v-model="sessionForm.name" :class="inputCls" /></label><div class="grid grid-cols-2 gap-4"><label class="block text-sm">Start Year<input v-model.number="sessionForm.startYear" type="number" :class="inputCls" /></label><label class="block text-sm">End Year<input v-model.number="sessionForm.endYear" type="number" :class="inputCls" /></label></div><label class="block text-sm">Status<select v-model="sessionForm.status" :class="inputCls"><option value="upcoming">Upcoming</option><option value="active">Active</option><option value="completed">Completed</option></select></label></template>
    <template v-else-if="modal === 'semesters'"><label class="block text-sm">Programme<select v-model="semesterForm.programmeId" :class="inputCls"><option v-for="item in programmes" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label class="block text-sm">Session<select v-model="semesterForm.sessionId" :class="inputCls"><option v-for="item in sessions" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><div class="grid grid-cols-2 gap-4"><label class="block text-sm">Number<input v-model.number="semesterForm.number" type="number" :class="inputCls" /></label><label class="block text-sm">Status<select v-model="semesterForm.status" :class="inputCls"><option value="open">Open</option><option value="closed">Closed</option><option value="results_published">Results Published</option></select></label></div></template>
    <template v-else><div class="grid grid-cols-2 gap-4"><label class="block text-sm">Code<input v-model="subjectForm.code" :class="inputCls" /></label><label class="block text-sm">Credits<input v-model.number="subjectForm.credits" type="number" :class="inputCls" /></label></div><label class="block text-sm">Title<input v-model="subjectForm.title" :class="inputCls" /></label><div class="grid grid-cols-2 gap-4"><label class="block text-sm">Programme<select v-model="subjectForm.programmeId" :class="inputCls"><option v-for="item in programmes" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label class="block text-sm">Semester<input v-model.number="subjectForm.semesterNumber" type="number" :class="inputCls" /></label></div><label class="block text-sm">Pass Mark<input v-model.number="subjectForm.passMark" type="number" :class="inputCls" /></label><div><div class="flex justify-between text-sm mb-2"><span>Assessment Components</span><button class="text-xs" @click="addComponent">+ Add Component</button></div><div v-for="(component, index) in subjectForm.components" :key="index" class="flex gap-2 mb-2"><input v-model="component.name" placeholder="Name" :class="inputCls" /><input v-model.number="component.maxMarks" type="number" placeholder="Max" class="w-24 border border-navy-200 rounded-lg px-3 py-2 text-sm" /></div><div class="text-xs text-navy-400">Total max marks: {{ subjectForm.components.reduce((sum, component) => sum + component.maxMarks, 0) }}</div></div></template>
    <div class="flex gap-3 pt-2"><button class="bg-navy-800 text-white px-4 py-2 rounded-lg text-sm" @click="save">Save</button><button class="text-navy-500 text-sm" @click="modal = null">Cancel</button></div>
  </div></div></div>
  </div>
</template>
