<script setup lang="ts">
import { computed, ref } from 'vue'
import { useAppStore } from '../../stores/appStore'
import { gradeColor } from '../../utils/calculations'
type ReportType = 'classwise' | 'individual' | 'subject' | 'passfail' | 'gpa' | 'pending' | 'published'
const { programmes, sessions, semesters, subjects, students, marksEntries, semesterResults } = useAppStore()
const reportType = ref<ReportType>('classwise')
const selProg = ref(programmes.value[0]?.id ?? ''), selSession = ref('s2'), selSem = ref('sem1'), selStudent = ref(students.value[0]?.id ?? '')
const filteredSems = computed(() => semesters.value.filter(item => item.programmeId === selProg.value && item.sessionId === selSession.value))
const activeSem = computed(() => filteredSems.value.find(item => item.id === selSem.value) ?? filteredSems.value[0])
const semSubjects = computed(() => subjects.value.filter(item => item.programmeId === selProg.value && item.semesterNumber === (activeSem.value?.number ?? 0)))
const semStudents = computed(() => students.value.filter(item => item.programmeId === selProg.value && item.status === 'active'))
const semResults = computed(() => semesterResults.value.filter(item => item.semesterId === activeSem.value?.id && item.sessionId === selSession.value))
const programme = computed(() => programmes.value.find(item => item.id === selProg.value)); const session = computed(() => sessions.value.find(item => item.id === selSession.value)); const selectedStudent = computed(() => students.value.find(item => item.id === selStudent.value)); const selectedResult = computed(() => semResults.value.find(item => item.studentId === selStudent.value))
const reportTypes = [{ id: 'classwise', label: 'Class Marksheet' }, { id: 'individual', label: 'Individual Marksheet' }, { id: 'subject', label: 'Subject-wise Marks' }, { id: 'passfail', label: 'Pass/Fail Summary' }, { id: 'gpa', label: 'GPA/CGPA Report' }, { id: 'pending', label: 'Pending Results' }, { id: 'published', label: 'Published Results' }] as { id: ReportType; label: string }[]
function entryFor(studentId: string, subjectId: string) { return marksEntries.value.find(entry => entry.studentId === studentId && entry.subjectId === subjectId && entry.semesterId === activeSem.value?.id) }
function className(gpa: number) { return gpa >= 3.5 ? 'First Class' : gpa >= 3 ? 'Second Class Upper' : gpa >= 2.5 ? 'Second Class Lower' : gpa >= 2 ? 'Third Class' : 'Below Average' }
function printReport() { window.print() }
</script>
<template>
  <div class="space-y-5"><div class="bg-white border border-navy-100 rounded-xl p-5 no-print"><div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-4"><label class="text-xs font-medium">Programme<select v-model="selProg" class="w-full border border-navy-200 rounded-lg px-3 py-2 mt-1"><option v-for="item in programmes" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label class="text-xs font-medium">Session<select v-model="selSession" class="w-full border border-navy-200 rounded-lg px-3 py-2 mt-1"><option v-for="item in sessions" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label class="text-xs font-medium">Semester<select v-model="selSem" class="w-full border border-navy-200 rounded-lg px-3 py-2 mt-1"><option v-for="item in filteredSems" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label v-if="reportType === 'individual'" class="text-xs font-medium">Student<select v-model="selStudent" class="w-full border border-navy-200 rounded-lg px-3 py-2 mt-1"><option v-for="item in semStudents" :key="item.id" :value="item.id">{{ item.name }}</option></select></label></div><div class="flex flex-wrap gap-2 justify-between"><div class="flex gap-2 flex-wrap"><button v-for="item in reportTypes" :key="item.id" class="px-3 py-1.5 rounded-lg text-xs font-medium" :class="reportType === item.id ? 'bg-navy-800 text-white' : 'bg-navy-50 text-navy-600'" @click="reportType = item.id">{{ item.label }}</button></div><button class="bg-gold-400 text-navy-950 px-4 py-1.5 rounded-lg text-xs font-medium" @click="printReport">🖨 Print / PDF</button></div></div>
  <div class="bg-white border border-navy-100 rounded-xl overflow-hidden" id="report-area"><div class="px-6 py-5 bg-navy-900 text-white text-center"><img src="/images/BlueCrest University.png" alt="BlueCrest University logo" class="w-18 h-18 object-contain mx-auto mb-3" /><div class="font-serif text-xl font-bold">BlueCrest University, Monrovia</div><div class="text-navy-300 text-xs mt-1 uppercase">Examination & Result Management System</div><div class="mt-3 text-sm">{{ programme?.name }} · {{ session?.name }} · {{ activeSem?.name }}</div><div class="text-navy-400 text-xs mt-1">{{ reportTypes.find(item => item.id === reportType)?.label }}</div></div><div class="p-6 overflow-x-auto">
    <table v-if="reportType === 'classwise'" class="w-full text-sm border-collapse"><thead><tr class="bg-navy-50 text-xs uppercase"><th class="px-4 py-3 text-left border">Roll No.</th><th class="px-4 py-3 text-left border">Student Name</th><th v-for="subject in semSubjects" :key="subject.id" class="px-3 py-3 border">{{ subject.code }}</th><th class="px-3 py-3 border">GPA</th><th class="px-3 py-3 border">Result</th></tr></thead><tbody><tr v-for="student in semStudents" :key="student.id"><td class="px-4 py-3 border font-mono text-xs">{{ student.rollNumber }}</td><td class="px-4 py-3 border font-medium">{{ student.name }}</td><td v-for="subject in semSubjects" :key="subject.id" class="px-3 py-3 border text-center">{{ entryFor(student.id, subject.id)?.totalMarks ?? '—' }}<span v-if="entryFor(student.id, subject.id)" class="block text-xs" :class="gradeColor(entryFor(student.id, subject.id)!.grade)">{{ entryFor(student.id, subject.id)?.grade }}</span></td><td class="px-3 py-3 border text-center">{{ semResults.find(result => result.studentId === student.id)?.gpa.toFixed(2) ?? '—' }}</td><td class="px-3 py-3 border text-center">{{ semResults.find(result => result.studentId === student.id)?.overallStatus?.toUpperCase() ?? '—' }}</td></tr></tbody></table>
    <div v-else-if="reportType === 'individual' && selectedStudent" class="max-w-3xl mx-auto"><div class="bg-navy-50 p-5 grid grid-cols-2 gap-4 text-sm"><div><span class="text-navy-400">Student</span><b class="block">{{ selectedStudent.name }}</b></div><div><span class="text-navy-400">Roll Number</span><b class="block">{{ selectedStudent.rollNumber }}</b></div><div><span class="text-navy-400">Student ID</span><b class="block">{{ selectedStudent.studentId }}</b></div><div><span class="text-navy-400">Programme</span><b class="block">{{ programme?.name }}</b></div></div><table class="w-full text-sm"><thead><tr class="bg-navy-800 text-white text-xs"><th class="px-4 py-3 text-left">Subject</th><th class="px-3 py-3">Marks</th><th class="px-3 py-3">Grade</th><th class="px-3 py-3">Points</th><th class="px-3 py-3">Status</th></tr></thead><tbody><tr v-for="subject in semSubjects" :key="subject.id"><td class="px-4 py-3">{{ subject.title }}</td><td class="px-3 py-3 text-center">{{ entryFor(selectedStudent.id, subject.id)?.totalMarks ?? '—' }}</td><td class="px-3 py-3 text-center" :class="entryFor(selectedStudent.id, subject.id) ? gradeColor(entryFor(selectedStudent.id, subject.id)!.grade) : ''">{{ entryFor(selectedStudent.id, subject.id)?.grade ?? '—' }}</td><td class="px-3 py-3 text-center">{{ entryFor(selectedStudent.id, subject.id)?.gradePoint.toFixed(1) ?? '—' }}</td><td class="px-3 py-3 text-center">{{ entryFor(selectedStudent.id, subject.id)?.status?.toUpperCase() ?? '—' }}</td></tr></tbody><tfoot v-if="selectedResult"><tr class="bg-navy-900 text-white"><td colspan="3" class="px-4 py-3">Semester Result</td><td class="px-3 py-3">GPA {{ selectedResult.gpa.toFixed(2) }}</td><td class="px-3 py-3">{{ selectedResult.overallStatus.toUpperCase() }}</td></tr></tfoot></table></div>
    <div v-else-if="reportType === 'passfail'"><div class="grid grid-cols-3 gap-4 mb-6"><div v-for="item in [['Total Students', semStudents.length], ['Pass', semResults.filter(result => result.overallStatus === 'pass').length], ['Fail', semResults.filter(result => result.overallStatus === 'fail').length]]" :key="item[0]" class="bg-navy-50 rounded-lg p-4 text-center"><div class="text-3xl font-serif font-bold">{{ item[1] }}</div><div class="text-xs text-navy-500">{{ item[0] }}</div></div></div><table class="w-full text-sm"><thead><tr class="bg-navy-50 text-xs"><th class="p-3 text-left">Roll No.</th><th class="p-3 text-left">Student</th><th class="p-3">GPA</th><th class="p-3">Credits</th><th class="p-3">Result</th></tr></thead><tbody><tr v-for="student in semStudents" :key="student.id"><td class="p-3">{{ student.rollNumber }}</td><td class="p-3">{{ student.name }}</td><td class="p-3 text-center">{{ semResults.find(result => result.studentId === student.id)?.gpa.toFixed(2) ?? '—' }}</td><td class="p-3 text-center">{{ semResults.find(result => result.studentId === student.id)?.earnedCredits ?? '—' }}</td><td class="p-3 text-center">{{ semResults.find(result => result.studentId === student.id)?.overallStatus?.toUpperCase() ?? '—' }}</td></tr></tbody></table></div>
    <table v-else-if="reportType === 'pending' || reportType === 'published'" class="w-full text-sm"><thead><tr class="bg-navy-50 text-xs"><th class="p-3 text-left">Student</th><th class="p-3 text-left">Student ID</th><th class="p-3">GPA</th><th class="p-3">CGPA</th><th class="p-3">Result</th><th class="p-3">Status</th></tr></thead><tbody><tr v-for="result in semResults.filter(item => reportType === 'pending' ? item.publicationStatus !== 'published' : item.publicationStatus === 'published')" :key="result.id"><td class="p-3">{{ students.find(student => student.id === result.studentId)?.name }}</td><td class="p-3 font-mono text-xs">{{ students.find(student => student.id === result.studentId)?.studentId }}</td><td class="p-3 text-center font-mono">{{ result.gpa.toFixed(2) }}</td><td class="p-3 text-center font-mono">{{ result.cgpa.toFixed(2) }}</td><td class="p-3 text-center">{{ result.overallStatus.toUpperCase() }}</td><td class="p-3 text-center"><span class="rounded-full px-2 py-0.5 text-xs" :class="result.publicationStatus === 'published' ? 'bg-emerald-50 text-emerald-700' : result.publicationStatus === 'approved' ? 'bg-blue-50 text-blue-700' : 'bg-amber-50 text-amber-700'">{{ result.publicationStatus }}</span></td></tr></tbody></table>
    <table v-else-if="reportType === 'gpa'" class="w-full text-sm"><thead><tr class="bg-navy-50 text-xs"><th class="p-3">Rank</th><th class="p-3 text-left">Student</th><th class="p-3 text-left">Roll No.</th><th class="p-3">GPA</th><th class="p-3">CGPA</th><th class="p-3">Class</th></tr></thead><tbody><tr v-for="(result, index) in [...semResults].sort((a, b) => b.gpa - a.gpa)" :key="result.id"><td class="p-3 text-center">{{ index + 1 }}</td><td class="p-3">{{ students.find(student => student.id === result.studentId)?.name }}</td><td class="p-3">{{ students.find(student => student.id === result.studentId)?.rollNumber }}</td><td class="p-3 text-center font-bold">{{ result.gpa.toFixed(2) }}</td><td class="p-3 text-center">{{ result.cgpa.toFixed(2) }}</td><td class="p-3 text-center">{{ className(result.gpa) }}</td></tr></tbody></table>
    <div v-else class="space-y-6"><div v-for="subject in semSubjects" :key="subject.id" class="border border-navy-100 rounded-lg overflow-hidden"><div class="bg-navy-800 text-white px-5 py-3"><span class="font-mono">{{ subject.code }}</span> · {{ subject.title }}</div><table class="w-full text-sm"><thead><tr class="bg-navy-50 text-xs"><th class="p-3 text-left">Student</th><th v-for="component in subject.components" :key="component.name" class="p-3">{{ component.name }}</th><th class="p-3">Total</th><th class="p-3">Grade</th></tr></thead><tbody><tr v-for="student in semStudents" :key="student.id"><td class="p-3">{{ student.name }}</td><td v-for="component in subject.components" :key="component.name" class="p-3 text-center">{{ entryFor(student.id, subject.id)?.components[component.name] ?? '—' }}</td><td class="p-3 text-center">{{ entryFor(student.id, subject.id)?.totalMarks ?? '—' }}</td><td class="p-3 text-center">{{ entryFor(student.id, subject.id)?.grade ?? '—' }}</td></tr></tbody></table></div></div>
  </div><div class="px-6 py-4 bg-navy-50 border-t text-xs text-navy-400 flex justify-between"><span>BlueCrest University — Examination & Result Management System</span><span>Generated: {{ new Date().toLocaleDateString('en-LR') }}</span></div></div>
  </div>
</template>
