<script setup lang="ts">
import { computed, ref } from 'vue'
import { useAppStore } from '../../stores/appStore'
import { gradeColor } from '../../utils/calculations'
const { programmes, sessions, semesters, subjects, students, marksEntries, semesterResults, processResults, approveResult, publishResult } = useAppStore()
const selProg = ref(programmes.value[0]?.id ?? ''), selSession = ref('s2'), selSem = ref('sem1'), processing = ref(false), msg = ref('')
const filteredSems = computed(() => semesters.value.filter(item => item.programmeId === selProg.value && item.sessionId === selSession.value))
const activeSem = computed(() => filteredSems.value.find(item => item.id === selSem.value) ?? filteredSems.value[0])
const semSubjects = computed(() => subjects.value.filter(item => item.programmeId === selProg.value && item.semesterNumber === (activeSem.value?.number ?? 0)))
const semStudents = computed(() => students.value.filter(item => item.programmeId === selProg.value && item.status === 'active'))
const semResults = computed(() => semesterResults.value.filter(item => item.semesterId === activeSem.value?.id && item.sessionId === selSession.value))
const completeness = computed(() => semStudents.value.map(student => ({ student, entries: marksEntries.value.filter(entry => entry.studentId === student.id && entry.semesterId === activeSem.value?.id), missing: semSubjects.value.filter(subject => !marksEntries.value.some(entry => entry.studentId === student.id && entry.subjectId === subject.id && entry.semesterId === activeSem.value?.id)) })))
const incompleteStudents = computed(() => completeness.value.filter(item => item.missing.length))
const completeStudents = computed(() => completeness.value.filter(item => !item.missing.length))
async function handleProcess() { if (!activeSem.value) return; if (incompleteStudents.value.length) { msg.value = `${incompleteStudents.value.length} student${incompleteStudents.value.length === 1 ? '' : 's'} have incomplete marks. Complete review before processing.`; return } processing.value = true; try { await processResults(activeSem.value.id, selSession.value); msg.value = 'Results processed successfully. Review below.' } catch (error) { msg.value = error instanceof Error ? error.message : 'Unable to process results.' } finally { processing.value = false; setTimeout(() => { msg.value = '' }, 4000) } }
function entryFor(studentId: string, subjectId: string) { return marksEntries.value.find(entry => entry.studentId === studentId && entry.subjectId === subjectId && entry.semesterId === activeSem.value?.id) }
</script>
<template>
  <div class="space-y-5"><div class="bg-white border border-navy-100 rounded-xl p-5"><h2 class="font-serif font-semibold mb-4">Select Semester to Process</h2><div class="grid grid-cols-3 gap-4 mb-4"><label class="text-xs font-medium">Programme<select v-model="selProg" class="w-full border border-navy-200 rounded-lg px-3 py-2 mt-1"><option v-for="item in programmes" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label class="text-xs font-medium">Session<select v-model="selSession" class="w-full border border-navy-200 rounded-lg px-3 py-2 mt-1"><option v-for="item in sessions" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label class="text-xs font-medium">Semester<select v-model="selSem" class="w-full border border-navy-200 rounded-lg px-3 py-2 mt-1"><option v-for="item in filteredSems" :key="item.id" :value="item.id">{{ item.name }}</option></select></label></div><div class="flex flex-wrap gap-3 items-center"><button class="bg-navy-800 text-white px-4 py-2 rounded-lg text-sm disabled:opacity-60" :disabled="processing || incompleteStudents.length > 0" @click="handleProcess">{{ processing ? 'Processing…' : '⚙️ Process / Recalculate Results' }}</button><span v-if="semResults.length && !incompleteStudents.length" class="rounded-lg bg-blue-50 px-3 py-2 text-sm text-blue-700">Processed results are ready for approval.</span><div v-if="msg" class="rounded-lg px-3 py-2 text-sm" :class="msg.includes('incomplete') ? 'bg-amber-50 text-amber-700' : 'bg-emerald-50 text-emerald-700'">{{ msg }}</div></div></div>
  <div class="grid grid-cols-2 gap-4 lg:grid-cols-4"><div class="rounded-xl border border-navy-100 bg-white p-4"><div class="text-2xl font-serif font-bold text-navy-900">{{ semStudents.length }}</div><div class="text-xs text-navy-500">Students selected</div></div><div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div class="text-2xl font-serif font-bold text-emerald-700">{{ completeStudents.length }}</div><div class="text-xs text-emerald-700">Complete results</div></div><div class="rounded-xl border border-amber-200 bg-amber-50 p-4"><div class="text-2xl font-serif font-bold text-amber-700">{{ incompleteStudents.length }}</div><div class="text-xs text-amber-700">Incomplete results</div></div><div class="rounded-xl border border-navy-100 bg-white p-4"><div class="text-2xl font-serif font-bold text-navy-900">{{ semSubjects.length }}</div><div class="text-xs text-navy-500">Courses expected</div></div></div>
  <div v-if="incompleteStudents.length" class="rounded-xl border border-amber-200 bg-amber-50 p-5"><h3 class="font-serif font-semibold text-amber-900">Incomplete marks detected</h3><p class="mt-1 text-sm text-amber-800">{{ incompleteStudents.length }} student{{ incompleteStudents.length === 1 ? '' : 's' }} cannot be processed until all course marks are entered.</p><div class="mt-3 grid gap-2 sm:grid-cols-2"><div v-for="item in incompleteStudents" :key="item.student.id" class="rounded-lg border border-amber-200 bg-white/60 px-3 py-2 text-xs text-amber-900"><span class="font-medium">{{ item.student.name }}</span><span class="text-amber-700"> · missing {{ item.missing.map(subject => subject.code).join(', ') }}</span></div></div></div>
  <div v-if="semResults.length" class="grid grid-cols-2 lg:grid-cols-4 gap-4"><div v-for="item in [{ label: 'Total Students', value: semResults.length }, { label: 'Pass', value: semResults.filter(result => result.overallStatus === 'pass').length }, { label: 'Fail', value: semResults.filter(result => result.overallStatus === 'fail').length }, { label: 'Published', value: semResults.filter(result => result.publicationStatus === 'published').length }]" :key="item.label" class="bg-white border border-navy-100 rounded-xl p-4"><div class="text-2xl font-serif font-bold">{{ item.value }}</div><div class="text-xs text-navy-500 mt-1">{{ item.label }}</div></div></div>
  <div v-if="semResults.length" class="bg-white border border-navy-100 rounded-xl overflow-hidden"><div class="px-5 py-4 border-b border-navy-100"><h3 class="font-serif font-semibold">{{ activeSem?.name }} Results — {{ programmes.find(item => item.id === selProg)?.name }}</h3><p class="text-navy-400 text-xs mt-0.5">Subjects: {{ semSubjects.map(item => item.code).join(', ') }}</p></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="text-xs text-navy-500 uppercase border-b border-navy-100 bg-navy-50/50"><th class="px-5 py-3 text-left">Student</th><th v-for="subject in semSubjects" :key="subject.id" class="px-3 py-3">{{ subject.code }}</th><th class="px-3 py-3">GPA</th><th class="px-3 py-3">CGPA</th><th class="px-3 py-3">Credits</th><th class="px-3 py-3">Result</th><th class="px-3 py-3">Status</th><th /></tr></thead><tbody class="divide-y divide-navy-50"><tr v-for="result in semResults" :key="result.id"><td class="px-5 py-3"><div class="font-medium">{{ semStudents.find(student => student.id === result.studentId)?.name }}</div><div class="text-xs text-navy-400">{{ semStudents.find(student => student.id === result.studentId)?.rollNumber }}</div></td><td v-for="subject in semSubjects" :key="subject.id" class="px-3 py-3 text-center"><template v-if="entryFor(result.studentId, subject.id)"><div class="text-xs">{{ entryFor(result.studentId, subject.id)?.totalMarks }}/{{ subject.components.reduce((sum, component) => sum + component.maxMarks, 0) }}</div><span class="text-xs font-mono" :class="gradeColor(entryFor(result.studentId, subject.id)!.grade)">{{ entryFor(result.studentId, subject.id)?.grade }}</span></template><span v-else>—</span></td><td class="px-3 py-3 font-mono">{{ result.gpa.toFixed(2) }}</td><td class="px-3 py-3 font-mono">{{ result.cgpa.toFixed(2) }}</td><td class="px-3 py-3 text-xs">{{ result.earnedCredits }}/{{ result.totalCredits }}</td><td class="px-3 py-3"><span class="text-xs rounded-full px-2 py-0.5" :class="result.overallStatus === 'pass' ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'">{{ result.overallStatus.toUpperCase() }}</span></td><td class="px-3 py-3"><span class="text-xs rounded-full px-2 py-0.5 bg-navy-50">{{ result.publicationStatus }}</span></td><td class="px-5 py-3"><button v-if="result.publicationStatus === 'draft'" class="text-xs text-amber-600" @click="approveResult(result.id)">Approve</button><button v-else-if="result.publicationStatus === 'approved'" class="text-xs text-emerald-600" @click="publishResult(result.id)">Publish</button></td></tr></tbody></table></div></div><div v-else class="bg-white border border-navy-100 rounded-xl p-12 text-center text-navy-500">⚙️ No results processed for this semester yet.</div>
  </div>
</template>
