<script setup lang="ts">
import { computed, ref } from 'vue'
import { useAppStore } from '../../stores/appStore'
const { programmes, sessions, semesters, students, semesterResults, currentUser, publishResult } = useAppStore()
const selSession = ref('s2'); const selSem = ref(''); const message = ref('')
const results = computed(() => semesterResults.value.filter(result => result.sessionId === selSession.value && (!selSem.value || result.semesterId === selSem.value)))
const ready = computed(() => results.value.filter(result => result.publicationStatus === 'approved'))
const published = computed(() => results.value.filter(result => result.publicationStatus === 'published'))
const sessionOptions = computed(() => sessions.value); const semesterOptions = computed(() => semesters.value.filter(semester => semester.sessionId === selSession.value))
const canPublish = computed(() => currentUser.value?.role === 'admin')
const pendingPublicationId = ref<string | null>(null)
const pendingPublication = computed(() => results.value.find(result => result.id === pendingPublicationId.value))
function publish(resultId: string) { if (!canPublish.value) { message.value = 'Only administrators can publish results.'; return }; pendingPublicationId.value = resultId }
function confirmPublication() { if (!pendingPublication.value) return; publishResult(pendingPublication.value.id); message.value = 'Result published successfully.'; pendingPublicationId.value = null }
</script>
<template>
  <div class="space-y-5"><section class="rounded-xl border border-navy-100 bg-white p-5"><div class="mb-4"><p class="text-xs font-medium uppercase tracking-wider text-gold-600">Official Release</p><h2 class="font-serif text-xl font-semibold text-navy-900">Result Publication</h2><p class="text-sm text-navy-500">Only approved results can be released to student result interfaces.</p></div><div class="grid grid-cols-2 gap-4"><label class="text-xs font-medium text-navy-600">Academic Session<select v-model="selSession" class="mt-1 w-full rounded-lg border border-navy-200 px-3 py-2 text-sm"><option v-for="session in sessionOptions" :key="session.id" :value="session.id">{{ session.name }}</option></select></label><label class="text-xs font-medium text-navy-600">Semester<select v-model="selSem" class="mt-1 w-full rounded-lg border border-navy-200 px-3 py-2 text-sm"><option value="">All semesters</option><option v-for="semester in semesterOptions" :key="semester.id" :value="semester.id">{{ semester.name }}</option></select></label></div><div class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3"><div class="rounded-lg border border-emerald-200 bg-emerald-50 p-4"><div class="text-2xl font-serif font-bold text-emerald-700">{{ ready.length }}</div><div class="text-xs text-emerald-700">Ready for publication</div></div><div class="rounded-lg border border-gold-200 bg-gold-50 p-4"><div class="text-2xl font-serif font-bold text-gold-700">{{ published.length }}</div><div class="text-xs text-gold-700">Published</div></div><div class="rounded-lg border border-navy-100 bg-navy-50 p-4"><div class="text-2xl font-serif font-bold text-navy-900">{{ results.filter(result => result.publicationStatus === 'draft').length }}</div><div class="text-xs text-navy-600">Awaiting approval</div></div></div><div v-if="message" class="mt-4 rounded-lg bg-gold-50 px-3 py-2 text-sm text-gold-700">{{ message }}</div></section>
+    <section class="overflow-hidden rounded-xl border border-navy-100 bg-white"><div class="overflow-x-auto"><table class="w-full min-w-190 text-sm"><thead><tr class="bg-navy-50/50 text-left text-xs uppercase tracking-wider text-navy-500"><th class="px-5 py-3">Student</th><th class="px-5 py-3">Programme</th><th class="px-3 py-3">Session</th><th class="px-3 py-3">Semester</th><th class="px-3 py-3">GPA</th><th class="px-3 py-3">CGPA</th><th class="px-3 py-3">Approval</th><th class="px-3 py-3">Publication</th><th class="px-5 py-3">Action</th></tr></thead><tbody class="divide-y divide-navy-50"><tr v-for="result in results" :key="result.id"><td class="px-5 py-3"><div class="font-medium text-navy-800">{{ students.find(student => student.id === result.studentId)?.name }}</div><div class="text-xs text-navy-400">{{ students.find(student => student.id === result.studentId)?.studentId }}</div></td><td class="px-5 py-3 text-xs">{{ programmes.find(programme => programme.id === students.find(student => student.id === result.studentId)?.programmeId)?.name }}</td><td class="px-3 py-3 text-xs">{{ sessions.find(session => session.id === result.sessionId)?.name }}</td><td class="px-3 py-3 text-xs">{{ semesters.find(semester => semester.id === result.semesterId)?.name }}</td><td class="px-3 py-3 font-mono">{{ result.gpa.toFixed(2) }}</td><td class="px-3 py-3 font-mono">{{ result.cgpa.toFixed(2) }}</td><td class="px-3 py-3"><span class="rounded-full px-2 py-0.5 text-xs" :class="result.publicationStatus === 'draft' ? 'bg-amber-50 text-amber-700' : 'bg-blue-50 text-blue-700'">{{ result.publicationStatus === 'draft' ? 'Pending' : 'Approved' }}</span></td><td class="px-3 py-3"><span class="rounded-full px-2 py-0.5 text-xs" :class="result.publicationStatus === 'published' ? 'bg-emerald-50 text-emerald-700' : 'bg-navy-50 text-navy-600'">{{ result.publicationStatus === 'published' ? 'Published' : 'Not published' }}</span><div v-if="result.publishedAt" class="mt-1 text-[10px] text-navy-400">{{ new Date(result.publishedAt).toLocaleDateString('en-LR') }}</div></td><td class="px-5 py-3"><button v-if="result.publicationStatus === 'approved'" class="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-medium text-white" @click="publish(result.id)">Publish</button><span v-else-if="result.publicationStatus === 'published'" class="text-xs text-emerald-700">Released</span><span v-else class="text-xs text-navy-400">Approval required</span></td></tr></tbody></table><div v-if="!results.length" class="p-12 text-center text-sm text-navy-400">No results are available for publication.</div></div></section>
    <div v-if="pendingPublication" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true" aria-labelledby="publication-dialog-title">
      <div class="w-full max-w-md rounded-xl bg-white shadow-xl">
        <div class="border-b border-navy-100 p-5"><p class="text-xs font-medium uppercase tracking-wider text-gold-600">Official Release</p><h3 id="publication-dialog-title" class="mt-1 font-serif text-lg font-semibold text-navy-900">Publish this result?</h3></div>
        <div class="space-y-3 p-5"><p class="text-sm text-navy-600">This result will become available to students through Result Verification.</p><div class="rounded-lg bg-navy-50 p-3 text-sm text-navy-700"><div class="font-medium">{{ students.find(student => student.id === pendingPublication?.studentId)?.name }}</div><div class="mt-1 text-xs text-navy-500">GPA {{ pendingPublication?.gpa.toFixed(2) }} · CGPA {{ pendingPublication?.cgpa.toFixed(2) }}</div></div></div>
        <div class="flex justify-end gap-3 border-t border-navy-100 p-5"><button class="rounded-lg border border-navy-200 px-4 py-2 text-sm text-navy-600" @click="pendingPublicationId = null">Cancel</button><button class="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white" @click="confirmPublication">Publish Result</button></div>
      </div>
    </div>
  </div>
</template>
