<script setup lang="ts">
import { computed, ref } from 'vue'
import { useAppStore } from '../../stores/appStore'
import type { User } from '../../types'
const inputCls = 'w-full border border-navy-200 rounded-lg px-3 py-2.5 text-sm text-navy-900 focus:outline-none focus:border-navy-500 transition-colors'
const permissions = ['marks_entry', 'view_students', 'reports', 'result_processing']
const { users, currentUser, setUsers, addAuditLog } = useAppStore()
const search = ref(''); const roleFilter = ref(''); const statusFilter = ref('')
const filteredUsers = computed(() => users.value.filter(user => (!search.value || `${user.name} ${user.email}`.toLowerCase().includes(search.value.toLowerCase())) && (!roleFilter.value || user.role === roleFilter.value) && (!statusFilter.value || user.status === statusFilter.value)))
const activeUsers = computed(() => users.value.filter(user => user.status === 'active').length)
const adminUsers = computed(() => users.value.filter(user => user.role === 'admin').length)
const modal = ref(false)
const editing = ref<string | null>(null)
const form = ref({ name: '', email: '', password: '', role: 'staff' as 'admin' | 'staff', permissions: ['marks_entry', 'view_students', 'reports'], status: 'active' as User['status'] })
function openAdd() { editing.value = null; form.value = { name: '', email: '', password: '', role: 'staff', permissions: ['marks_entry', 'view_students', 'reports'], status: 'active' }; modal.value = true }
function openEdit(user: User) { editing.value = user.id; form.value = { name: user.name, email: user.email, password: user.password, role: user.role, permissions: [...user.permissions], status: user.status }; modal.value = true }
function save() { if (!form.value.name || !form.value.email) return; if (editing.value) { setUsers(items => items.map(user => user.id === editing.value ? { ...user, ...form.value } : user)); addAuditLog('UPDATE_USER', 'UserManagement', `Updated account ${form.value.email}`) } else { setUsers(items => [...items, { id: `u${Date.now()}`, ...form.value, createdAt: new Date().toISOString() }]); addAuditLog('CREATE_USER', 'UserManagement', `Created account ${form.value.email}`) }; modal.value = false }
function togglePermission(permission: string) { form.value.permissions = form.value.permissions.includes(permission) ? form.value.permissions.filter(item => item !== permission) : [...form.value.permissions, permission] }
function toggleStatus(id: string) { const user = users.value.find(item => item.id === id); if (!user || !window.confirm(`${user.status === 'active' ? 'Deactivate' : 'Activate'} ${user.name}?`)) return; setUsers(items => items.map(item => item.id === id ? { ...item, status: item.status === 'active' ? 'inactive' : 'active' } : item)); addAuditLog(user.status === 'active' ? 'DEACTIVATE_USER' : 'ACTIVATE_USER', 'UserManagement', `${user.name} account status changed`) }
</script>
<template>
  <div class="space-y-5"><div class="bg-white border border-navy-100 rounded-xl p-5 flex items-center justify-between"><div><h2 class="font-serif text-navy-900 font-semibold">System Users</h2><p class="text-navy-400 text-xs mt-0.5">Manage admin and staff accounts</p></div><button class="bg-navy-800 hover:bg-navy-700 text-white px-4 py-2 rounded-lg text-sm font-medium" @click="openAdd">+ Add User</button></div>
    <div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div class="rounded-xl border border-navy-100 bg-white p-4"><div class="text-2xl font-serif font-bold text-navy-900">{{ users.length }}</div><div class="text-xs text-navy-500">Total users</div></div><div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div class="text-2xl font-serif font-bold text-emerald-700">{{ activeUsers }}</div><div class="text-xs text-emerald-700">Active users</div></div><div class="rounded-xl border border-navy-100 bg-white p-4"><div class="text-2xl font-serif font-bold text-navy-900">{{ users.length - activeUsers }}</div><div class="text-xs text-navy-500">Inactive users</div></div><div class="rounded-xl border border-gold-200 bg-gold-50 p-4"><div class="text-2xl font-serif font-bold text-gold-700">{{ adminUsers }}</div><div class="text-xs text-gold-700">Administrators</div></div></div>
    <div class="flex flex-col gap-3 rounded-xl border border-navy-100 bg-white p-4 md:flex-row"><input v-model="search" class="flex-1 rounded-lg border border-navy-200 px-3 py-2 text-sm" placeholder="Search by name or email" /><select v-model="roleFilter" class="rounded-lg border border-navy-200 px-3 py-2 text-sm"><option value="">All roles</option><option value="admin">Administrator</option><option value="staff">Staff</option></select><select v-model="statusFilter" class="rounded-lg border border-navy-200 px-3 py-2 text-sm"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
    <div class="bg-amber-50 border border-amber-200 rounded-xl p-4 text-sm text-amber-800 flex gap-3"><span>⚠️</span><div><div class="font-medium">Access Control Notice</div><div class="text-xs mt-0.5 text-amber-700">System supports 1 Admin and up to 2 Staff accounts. Students access results through the public verification page only.</div></div></div>
    <div class="grid gap-4"><div v-for="user in filteredUsers" :key="user.id" class="bg-white border border-navy-100 rounded-xl p-5" :class="user.status === 'inactive' ? 'opacity-60' : ''"><div class="flex items-start justify-between gap-4"><div class="flex items-center gap-4"><div class="w-12 h-12 rounded-full flex items-center justify-center text-lg font-serif font-bold" :class="user.role === 'admin' ? 'bg-gold-100 text-gold-700' : 'bg-navy-100 text-navy-600'">{{ user.name.split(' ').map(name => name[0]).slice(0, 2).join('') }}</div><div><div class="flex items-center gap-2 flex-wrap"><span class="font-medium text-navy-900">{{ user.name }}</span><span v-if="user.id === currentUser?.id" class="text-xs bg-navy-800 text-white px-2 py-0.5 rounded-full">You</span><span class="text-xs px-2 py-0.5 rounded-full bg-navy-50 text-navy-600">{{ user.role }}</span><span class="text-xs px-2 py-0.5 rounded-full" :class="user.status === 'active' ? 'bg-emerald-50 text-emerald-700' : 'bg-gray-100 text-gray-500'">{{ user.status }}</span></div><div class="text-navy-400 text-xs mt-1">{{ user.email }}</div><div class="flex flex-wrap gap-1.5 mt-2"><span v-if="user.role === 'admin'" class="text-xs bg-gold-50 text-gold-600 border border-gold-200 px-2 py-0.5 rounded">Full Access</span><span v-for="permission in user.permissions" v-else :key="permission" class="text-xs bg-navy-50 text-navy-600 px-2 py-0.5 rounded">{{ permission.replace('_', ' ') }}</span></div></div></div><div class="flex flex-col items-end gap-2"><div class="flex gap-2"><button class="text-xs text-navy-500 border border-navy-200 px-3 py-1 rounded-lg" @click="openEdit(user)">Edit</button><button v-if="user.id !== currentUser?.id" class="text-xs border px-3 py-1 rounded-lg" :class="user.status === 'active' ? 'text-red-500 border-red-200' : 'text-emerald-600 border-emerald-200'" @click="toggleStatus(user.id)">{{ user.status === 'active' ? 'Deactivate' : 'Activate' }}</button></div><div class="text-xs text-navy-300 font-mono">Joined {{ new Date(user.createdAt).toLocaleDateString('en-LR', { month: 'short', year: 'numeric' }) }}</div></div></div></div></div>
    <div v-if="modal" class="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4"><div class="bg-white rounded-xl shadow-xl w-full max-w-md"><div class="flex items-center justify-between p-5 border-b border-navy-100"><h3 class="font-serif text-navy-900 font-semibold">{{ editing ? 'Edit User' : 'Add Staff User' }}</h3><button class="text-navy-400 text-xl" @click="modal = false">×</button></div><div class="p-5 space-y-4"><div><label class="block text-sm font-medium text-navy-700 mb-1.5">Full Name</label><input v-model="form.name" :class="inputCls" /></div><div><label class="block text-sm font-medium text-navy-700 mb-1.5">Email Address</label><input v-model="form.email" type="email" :class="inputCls" /></div><div><label class="block text-sm font-medium text-navy-700 mb-1.5">Password</label><input v-model="form.password" type="password" :class="inputCls" /></div><div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-navy-700 mb-1.5">Role</label><select v-model="form.role" :class="inputCls"><option value="staff">Staff</option><option value="admin">Admin</option></select></div><div><label class="block text-sm font-medium text-navy-700 mb-1.5">Status</label><select v-model="form.status" :class="inputCls"><option value="active">Active</option><option value="inactive">Inactive</option></select></div></div><div v-if="form.role === 'staff'"><label class="block text-sm font-medium text-navy-700 mb-2">Permissions</label><label v-for="permission in permissions" :key="permission" class="flex items-center gap-2 mb-2"><input type="checkbox" :checked="form.permissions.includes(permission)" @change="togglePermission(permission)" /><span class="text-sm text-navy-700">{{ permission.replace(/_/g, ' ') }}</span></label></div><div class="flex gap-3 pt-2"><button class="bg-navy-800 text-white px-4 py-2 rounded-lg text-sm font-medium" @click="save">{{ editing ? 'Update User' : 'Create User' }}</button><button class="text-navy-500 text-sm" @click="modal = false">Cancel</button></div></div></div></div>
  </div>
</template>
