<script setup lang="ts">
import { computed } from 'vue'
import { useAppStore } from '../../stores/appStore'
const { currentUser, programmes, students, marksEntries, semesters, subjects, sessions, semesterResults, auditLogs, navigate } = useAppStore()
const currentSession = computed(() => sessions.value.find(session => session.status === 'active'))
const currentSemester = computed(() => semesters.value.find(semester => semester.sessionId === currentSession.value?.id && semester.status === 'open') ?? semesters.value.find(semester => semester.sessionId === currentSession.value?.id))
const activeStudents = computed(() => students.value.filter(student => student.status === 'active'))
const pendingMarks = computed(() => activeStudents.value.reduce((total, student) => { const expected = subjects.value.filter(subject => subject.programmeId === student.programmeId && subject.semesterNumber === student.currentSemester); const semesterIds = semesters.value.filter(semester => semester.programmeId === student.programmeId && semester.number === student.currentSemester).map(semester => semester.id); const entered = marksEntries.value.filter(entry => entry.studentId === student.id && semesterIds.includes(entry.semesterId)); return total + Math.max(expected.length - entered.length, 0) }, 0))
const completeMarks = computed(() => marksEntries.value.length)
const pendingReview = computed(() => semesterResults.value.filter(result => result.publicationStatus === 'draft').length)
const processedResults = computed(() => semesterResults.value.length)
const stats = computed(() => [['Students', activeStudents.value.length], ['Courses', subjects.value.length], ['Pending Marks', pendingMarks.value], ['Marks Entered', completeMarks.value], ['Awaiting Review', pendingReview.value], ['Results Processed', processedResults.value]])
const recentActivity = computed(() => auditLogs.value.slice(0, 5))
const quickActions = [{ label: 'Enter Marks', page: 'marks-entry', icon: 'M' }, { label: 'Review Marks', page: 'marks-review', icon: 'V' }, { label: 'Process Results', page: 'result-processing', icon: 'R' }, { label: 'View Students', page: 'staff-students', icon: 'S' }, { label: 'View Courses', page: 'staff-courses', icon: 'C' }, { label: 'Open Reports', page: 'reports', icon: 'P' }]
</script>
<template>
  <div class="space-y-6"><section class="rounded-xl bg-navy-800 p-6 text-white"><div class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-xs font-medium uppercase tracking-[0.18em] text-gold-300">Examination Office</p><div class="mt-1 font-serif text-2xl font-bold">Welcome back, {{ currentUser?.name }}</div><p class="mt-1 text-sm capitalize text-navy-300">{{ currentUser?.role }} · operational workspace</p></div><div class="rounded-lg border border-navy-600 bg-navy-700/60 px-4 py-3 text-sm"><div class="text-xs text-navy-300">Current academic context</div><div class="font-semibold text-white">{{ currentSession?.name ?? 'No active session' }}</div><div class="text-xs text-navy-300">{{ currentSemester?.name ?? 'No active semester' }}</div></div></div><div class="mt-5 flex flex-wrap gap-2"><span v-for="permission in currentUser?.permissions" :key="permission" class="rounded-full bg-navy-700 px-3 py-1 text-xs text-navy-200">{{ permission.replace(/_/g, ' ') }}</span></div></section>
  <section class="grid grid-cols-2 gap-3 xl:grid-cols-6"><div v-for="stat in stats" :key="stat[0]" class="rounded-xl border border-navy-100 bg-white p-4"><div class="text-2xl font-serif font-bold text-navy-900">{{ stat[1] }}</div><div class="mt-1 text-xs text-navy-500">{{ stat[0] }}</div></div></section>
  <section><div class="mb-3"><h2 class="font-serif font-semibold text-navy-900">Quick Actions</h2><p class="text-xs text-navy-400">Jump directly to common examination-office tasks.</p></div><div class="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6"><button v-for="action in quickActions" :key="action.page" class="rounded-xl border border-navy-100 bg-white p-4 text-left transition hover:border-gold-300 hover:bg-gold-50" @click="navigate(action.page)"><span class="flex h-8 w-8 items-center justify-center rounded-lg bg-navy-800 font-mono text-sm text-gold-300">{{ action.icon }}</span><span class="mt-3 block text-xs font-semibold text-navy-800">{{ action.label }}</span></button></div></section>
  <section class="grid grid-cols-1 gap-6 lg:grid-cols-2"><div class="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 class="font-serif font-semibold text-amber-900">Pending Work</h2><p class="mt-1 text-xs text-amber-700">Items that may require examination-office attention.</p><div class="mt-4 space-y-3"><button class="flex w-full items-center justify-between rounded-lg border border-amber-200 bg-white/70 p-3 text-left" @click="navigate('marks-entry')"><span><span class="block text-sm font-medium text-amber-900">Pending marks</span><span class="block text-xs text-amber-700">Student/course entries outstanding</span></span><span class="font-mono text-lg font-bold text-amber-700">{{ pendingMarks }}</span></button><button class="flex w-full items-center justify-between rounded-lg border border-amber-200 bg-white/70 p-3 text-left" @click="navigate('marks-review')"><span><span class="block text-sm font-medium text-amber-900">Results awaiting review</span><span class="block text-xs text-amber-700">Processed records in draft status</span></span><span class="font-mono text-lg font-bold text-amber-700">{{ pendingReview }}</span></button></div></div><div class="rounded-xl border border-navy-100 bg-white p-5"><div class="mb-4 flex items-center justify-between"><div><h2 class="font-serif font-semibold text-navy-900">Recent Activity</h2><p class="text-xs text-navy-400">Latest examination-office events</p></div><button class="text-xs text-navy-500" @click="navigate('reports')">Reports →</button></div><div v-if="recentActivity.length" class="space-y-3"><div v-for="activity in recentActivity" :key="activity.id" class="flex gap-3"><div class="mt-1 h-2 w-2 shrink-0 rounded-full bg-gold-400" /><div><div class="text-xs font-medium text-navy-800">{{ activity.action.replace(/_/g, ' ') }}</div><div class="text-xs text-navy-500">{{ activity.details }}</div></div></div></div><div v-else class="py-8 text-center text-xs text-navy-400">No recent activity recorded.</div></div></section>
  </div>
</template>
