<script setup lang="ts">
import { computed, ref } from 'vue'
import { useAppStore } from '../../stores/appStore'
const { students, programmes, sessions } = useAppStore()
const search = ref(''); const programmeFilter = ref(''); const statusFilter = ref('')
const filtered = computed(() => students.value.filter(student => (!search.value || `${student.name} ${student.studentId} ${student.rollNumber}`.toLowerCase().includes(search.value.toLowerCase())) && (!programmeFilter.value || student.programmeId === programmeFilter.value) && (!statusFilter.value || student.status === statusFilter.value)))
</script>
<template>
  <div class="space-y-5"><div><p class="text-xs font-medium uppercase tracking-wider text-gold-600">Academic Records</p><h2 class="font-serif text-2xl font-semibold text-navy-900">Students</h2><p class="text-sm text-navy-500">Search student records relevant to examination operations.</p></div><div class="flex flex-col gap-3 rounded-xl border border-navy-100 bg-white p-4 md:flex-row"><input v-model="search" class="flex-1 rounded-lg border border-navy-200 px-3 py-2 text-sm" placeholder="Search name, student ID, or roll number" /><select v-model="programmeFilter" class="rounded-lg border border-navy-200 px-3 py-2 text-sm"><option value="">All programmes</option><option v-for="programme in programmes" :key="programme.id" :value="programme.id">{{ programme.name }}</option></select><select v-model="statusFilter" class="rounded-lg border border-navy-200 px-3 py-2 text-sm"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="graduated">Graduated</option></select></div><div class="overflow-hidden rounded-xl border border-navy-100 bg-white"><div class="overflow-x-auto"><table class="w-full min-w-190 text-sm"><thead><tr class="bg-navy-50/50 text-left text-xs uppercase tracking-wider text-navy-500"><th class="px-5 py-3">Student</th><th class="px-5 py-3">Registration</th><th class="px-5 py-3">Programme</th><th class="px-5 py-3">Session</th><th class="px-5 py-3">Semester</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-navy-50"><tr v-for="student in filtered" :key="student.id"><td class="px-5 py-3"><div class="font-medium text-navy-800">{{ student.name }}</div><div class="text-xs text-navy-400">{{ student.email }}</div></td><td class="px-5 py-3 font-mono text-xs">{{ student.studentId }}<div class="text-navy-400">{{ student.rollNumber }}</div></td><td class="px-5 py-3 text-xs">{{ programmes.find(programme => programme.id === student.programmeId)?.name }}</td><td class="px-5 py-3 text-xs">{{ sessions.find(session => session.id === student.sessionId)?.name }}</td><td class="px-5 py-3">Sem {{ student.currentSemester }}</td><td class="px-5 py-3"><span class="rounded-full px-2 py-0.5 text-xs" :class="student.status === 'active' ? 'bg-emerald-50 text-emerald-700' : 'bg-navy-50 text-navy-500'">{{ student.status }}</span></td></tr></tbody></table><div v-if="!filtered.length" class="p-12 text-center text-sm text-navy-400">No students found.</div></div></div></div>
</template>
