<script setup lang="ts">
import { computed, ref } from 'vue'
import { useAppStore } from '../../stores/appStore'
const { students, programmes, semesters, sessions, semesterResults } = useAppStore()
const search = ref(''); const statusFilter = ref('')
const rows = computed(() => semesterResults.value.map(result => { const student = students.value.find(item => item.id === result.studentId); return { result, student, programme: programmes.value.find(item => item.id === student?.programmeId), semester: semesters.value.find(item => item.id === result.semesterId), session: sessions.value.find(item => item.id === result.sessionId) } }).filter(row => row.student && (!search.value || `${row.student.name} ${row.student.studentId} ${row.student.rollNumber}`.toLowerCase().includes(search.value.toLowerCase())) && (!statusFilter.value || (statusFilter.value === 'processed' ? row.result.publicationStatus === 'draft' : row.result.publicationStatus === statusFilter.value))))
</script>
<template>
  <div class="space-y-5"><div><p class="text-xs font-medium uppercase tracking-wider text-gold-600">Result Management</p><h2 class="font-serif text-2xl font-semibold text-navy-900">Result Verification</h2><p class="text-sm text-navy-500">Inspect processing, approval, and publication status without changing results.</p></div><div class="flex flex-col gap-3 rounded-xl border border-navy-100 bg-white p-4 md:flex-row"><input v-model="search" class="flex-1 rounded-lg border border-navy-200 px-3 py-2 text-sm" placeholder="Search student name, ID, or roll number" /><select v-model="statusFilter" class="rounded-lg border border-navy-200 px-3 py-2 text-sm"><option value="">All statuses</option><option value="processed">Processed</option><option value="approved">Approved</option><option value="published">Published</option></select></div><div class="overflow-hidden rounded-xl border border-navy-100 bg-white"><div class="overflow-x-auto"><table class="w-full min-w-190 text-sm"><thead><tr class="bg-navy-50/50 text-left text-xs uppercase tracking-wider text-navy-500"><th class="px-5 py-3">Student</th><th class="px-5 py-3">Programme</th><th class="px-3 py-3">Session</th><th class="px-3 py-3">Semester</th><th class="px-3 py-3">GPA</th><th class="px-3 py-3">CGPA</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-navy-50"><tr v-for="row in rows" :key="row.result.id"><td class="px-5 py-3"><div class="font-medium text-navy-800">{{ row.student?.name }}</div><div class="text-xs text-navy-400">{{ row.student?.studentId }}</div></td><td class="px-5 py-3 text-xs">{{ row.programme?.name }}</td><td class="px-3 py-3 text-xs">{{ row.session?.name }}</td><td class="px-3 py-3 text-xs">{{ row.semester?.name }}</td><td class="px-3 py-3 font-mono">{{ row.result.gpa.toFixed(2) }}</td><td class="px-3 py-3 font-mono">{{ row.result.cgpa.toFixed(2) }}</td><td class="px-5 py-3"><span class="rounded-full px-2 py-0.5 text-xs" :class="row.result.publicationStatus === 'published' ? 'bg-emerald-50 text-emerald-700' : row.result.publicationStatus === 'approved' ? 'bg-blue-50 text-blue-700' : 'bg-amber-50 text-amber-700'">{{ row.result.publicationStatus === 'draft' ? 'Processed' : row.result.publicationStatus }}</span></td></tr></tbody></table><div v-if="!rows.length" class="p-12 text-center text-sm text-navy-400">No results found.</div></div></div></div>
</template>
