<script setup lang="ts">
import { computed, ref } from 'vue'
import { useAppStore } from '../../stores/appStore'
const { subjects, programmes, semesters } = useAppStore()
const search = ref(''); const programmeFilter = ref('')
const filtered = computed(() => subjects.value.filter(subject => (!search.value || `${subject.code} ${subject.title}`.toLowerCase().includes(search.value.toLowerCase())) && (!programmeFilter.value || subject.programmeId === programmeFilter.value)))
</script>
<template>
  <div class="space-y-5"><div><p class="text-xs font-medium uppercase tracking-wider text-gold-600">Academic Records</p><h2 class="font-serif text-2xl font-semibold text-navy-900">Courses / Subjects</h2><p class="text-sm text-navy-500">Operational course reference for marks and examination work.</p></div><div class="flex flex-col gap-3 rounded-xl border border-navy-100 bg-white p-4 md:flex-row"><input v-model="search" class="flex-1 rounded-lg border border-navy-200 px-3 py-2 text-sm" placeholder="Search course code or title" /><select v-model="programmeFilter" class="rounded-lg border border-navy-200 px-3 py-2 text-sm"><option value="">All programmes</option><option v-for="programme in programmes" :key="programme.id" :value="programme.id">{{ programme.name }}</option></select></div><div class="overflow-hidden rounded-xl border border-navy-100 bg-white"><div class="overflow-x-auto"><table class="w-full min-w-190 text-sm"><thead><tr class="bg-navy-50/50 text-left text-xs uppercase tracking-wider text-navy-500"><th class="px-5 py-3">Course</th><th class="px-5 py-3">Title</th><th class="px-3 py-3">Credits</th><th class="px-3 py-3">Programme</th><th class="px-3 py-3">Semester</th><th class="px-3 py-3">Assessment</th></tr></thead><tbody class="divide-y divide-navy-50"><tr v-for="subject in filtered" :key="subject.id"><td class="px-5 py-3 font-mono text-xs font-semibold">{{ subject.code }}</td><td class="px-5 py-3 text-navy-800">{{ subject.title }}</td><td class="px-3 py-3 text-center">{{ subject.credits }}</td><td class="px-3 py-3 text-xs">{{ programmes.find(programme => programme.id === subject.programmeId)?.name }}</td><td class="px-3 py-3">{{ semesters.find(semester => semester.programmeId === subject.programmeId && semester.number === subject.semesterNumber)?.name ?? `Semester ${subject.semesterNumber}` }}</td><td class="px-3 py-3 text-xs text-navy-500">{{ subject.components.map(component => `${component.name} / ${component.maxMarks}`).join(' · ') }}</td></tr></tbody></table><div v-if="!filtered.length" class="p-12 text-center text-sm text-navy-400">No courses found.</div></div></div></div>
</template>
